"""
Sphinx configuration file for the Pyrite documentation.
"""

import os
import sys
from pathlib import Path

# Add the src directory to the path so Sphinx can find your modules if needed later
sys.path.insert(0, os.path.abspath('../src'))

project = 'Pyrite'
copyright = '2026, ShivamKR12'
author = 'ShivamKR12'
version = '1.0'
release = '1.0.0'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.mermaid',
    'sphinx.ext.graphviz',
    'sphinxcontrib.plantuml',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The Read the Docs theme provides the collapsible sidebar, search, and next/prev links!
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_css_files = ['custom.css']

html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
}

# MathJax for formula rendering
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

# Output file base name for HTML build
html_logo = None

# Docstring processing
autodoc_typehints = 'description'
autodoc_member_order = 'bysource'

# Mermaid version for GitHub Pages compatibility
mermaid_version = '10.9.0'

# Intersphinx mapping for external documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pygame': ('https://www.pyga.me/docs/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}


# Ensure generated API index has a friendly title when building locally or in CI.


def _normalize_api_index_title(app):
    p = Path(__file__).parent / 'api' / 'modules.rst'
    if p.exists():
        s = p.read_text(encoding='utf8').splitlines()
        # find first non-empty line (the autogenerated title) and replace it
        for i, line in enumerate(s):
            if line.strip():
                title_idx = i
                break
        else:
            title_idx = None
        if title_idx is not None:
            new_title = 'API Reference'
            s[title_idx] = new_title
            if title_idx + 1 < len(s):
                s[title_idx + 1] = '=' * len(new_title)
            else:
                s.insert(title_idx + 1, '=' * len(new_title))
            p.write_text('\n'.join(s) + '\n', encoding='utf8')
            print('Normalized docs/api/modules.rst title to "API Reference"')
    else:
        print('docs/api/modules.rst not found; skipping title normalization')


def setup(app):
    app.connect('builder-inited', _normalize_api_index_title)
