name: Mypy Type Checking

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Static type checking with Mypy
      run: mypy src/
